name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  build_container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: make build
