name: Docker Build

on:
  pull_request:
    branches:
      - master

jobs:
  build_container:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile

      - name: Build Image
        run: make build
